# Generated by Django 2.1.7 on 2019-09-26 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expression',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='expression',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expression',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='adiviname.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
