# Generated by Django 2.1.7 on 2019-09-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0002_auto_20190926_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameClick',
            fields=[
                ('game_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='click', serialize=False, to='adiviname.Game')),
                ('num_clicks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
