# Generated by Django 2.1.7 on 2019-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0004_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameclick',
            name='num_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
