# Generated by Django 2.1.7 on 2019-09-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0005_auto_20190927_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameclick',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
