# Generated by Django 2.1.7 on 2019-10-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0006_gameclick_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameclick',
            name='game_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clicks', serialize=False, to='adiviname.Game'),
        ),
    ]
