# Generated by Django 2.1.7 on 2019-10-05 18:46

import adiviname.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0007_auto_20191002_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='expressions_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
