# Generated by Django 2.1.7 on 2019-10-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0008_auto_20191005_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
