# Generated by Django 2.1.7 on 2019-10-05 19:29

import adiviname.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adiviname', '0009_remove_game_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(blank=True, max_length=254, null=True, upload_to=adiviname.models.iconName)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.AddField(
            model_name='gameicon',
            name='game_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='adiviname.Game'),
        ),
    ]
