# Generated by Django 2.1.7 on 2019-10-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0010_auto_20191005_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameicon',
            old_name='game_id',
            new_name='game',
        ),
    ]
