# Generated by Django 2.1.7 on 2020-04-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0013_auto_20200412_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='adiviname.GameIconBase'),
        ),
    ]
