# Generated by Django 2.1.7 on 2020-04-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiviname', '0015_auto_20200412_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='examples',
            field=models.CharField(default='Palabra 1, palabra 2, palabra 3...', max_length=100),
            preserve_default=False,
        ),
    ]
